defaults:
  - _self_
  - env: env_im
  - robot: smpl_humanoid
  - learning: im_mlp

notes: "Default Notes"
project: phc_mjx
exp_name: &exp_name humanoid_smpl
headless: True
seed: 0
no_log: False
resume_str: null
num_threads: 64
test: False 
output_dir: outputs/${exp_name}
epoch: 0
im_eval: False

hydra:
  job:
    name: ${exp_name}
    env_set:
      OMP_NUM_THREADS: 1
  run:
    dir: outputs/${exp_name}

